version: '3.8'

services:
    run:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./.keys:/app/.keys:ro
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        profiles:
            - command
